services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: xxx123456
    command: >
      --character-set-server=utf8mb4 
      --collation-server=utf8mb4_unicode_ci 
      --sql-mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
      --bind-address=0.0.0.0
    ports:
      - 3306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql

  nginx:
    image: nginx
    volumes: 
      - ./nginx:/etc/nginx
    ports:
      - "80:80"
      - "443:443"
    restart: always

  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - 6379:6379
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: xxx123456
      PGDATA: /var/lib/postgres/data/pgdata
    volumes:
      - ./pg/data:/var/lib/postgres/data
      - ./pg/etc:/etc/postgresql/postgresql.conf
    
  